# Load joint trajectory controller
controller_list:
  - name: pr2/right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_upper_arm_roll_joint
      - right_elbow_flex_joint
      - right_forearm_roll_joint
      - right_wrist_flex_joint
      - right_wrist_roll_joint
  - name: pr2/left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_upper_arm_roll_joint
      - left_elbow_flex_joint
      - left_forearm_roll_joint
      - left_wrist_flex_joint
      - left_wrist_roll_joint

  - name: pr2/right_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_right_gripper_finger_joint
      - right_left_gripper_finger_joint

  - name: pr2/left_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_right_gripper_finger_joint
      - left_left_gripper_finger_joint
