# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  left_elbow_flex_joint:
    has_velocity_limits: true
    max_velocity: 3.3
    has_acceleration_limits: false
    max_acceleration: 0
  left_forearm_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.6
    has_acceleration_limits: false
    max_acceleration: 0
  left_left_gripper_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: false
    max_acceleration: 0
  left_right_gripper_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: false
    max_acceleration: 0
  left_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.082
    has_acceleration_limits: false
    max_acceleration: 0
  left_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.088
    has_acceleration_limits: false
    max_acceleration: 0
  left_upper_arm_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.27
    has_acceleration_limits: false
    max_acceleration: 0
  left_wrist_flex_joint:
    has_velocity_limits: true
    max_velocity: 3.078
    has_acceleration_limits: false
    max_acceleration: 0
  left_wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.6
    has_acceleration_limits: false
    max_acceleration: 0
  right_elbow_flex_joint:
    has_velocity_limits: true
    max_velocity: 3.3
    has_acceleration_limits: false
    max_acceleration: 0
  right_forearm_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.6
    has_acceleration_limits: false
    max_acceleration: 0
  right_left_gripper_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: false
    max_acceleration: 0
  right_right_gripper_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: false
    max_acceleration: 0
  right_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.082
    has_acceleration_limits: false
    max_acceleration: 0
  right_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.088
    has_acceleration_limits: false
    max_acceleration: 0
  right_upper_arm_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.27
    has_acceleration_limits: false
    max_acceleration: 0
  right_wrist_flex_joint:
    has_velocity_limits: true
    max_velocity: 3.078
    has_acceleration_limits: false
    max_acceleration: 0
  right_wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.6
    has_acceleration_limits: false
    max_acceleration: 0