<?xml version="1.0"?>
<robot name="sensor_stick" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!--Define constants-->
  <xacro:property name="PI" value="3.14159"/>
  <xacro:property name="mass1" value="10" />
  <xacro:property name="mass2" value="1" />
  <xacro:property name="width1" value="0.1" /> <!--link_1 radius-->
  <xacro:property name="width2" value="0.1" /> <!--link_2 radius-->
  <xacro:property name="length0" value="0.1" /> <!--link_1 length-->
  <xacro:property name="length1" value="1.5" /> <!--link_2 length-->
  <xacro:property name="length2" value="0.1" /> <!--link_3 length-->
  <xacro:property name="mass_camera" value="0.2" />

  <!--Import gazebo elements-->
  <xacro:include filename="$(find sensor_stick)/urdf/sensor_stick.gazebo.xacro" />

  <!--Links-->
  <link name="world"/>

  <link name="link_1">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width1} ${width1} ${length1}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width1} ${width1} ${length1}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass1}"/>
      <inertia
        ixx="${mass1 / 12.0 * (width1*width1 + length1*length1)}" ixy="0.0" ixz="0.0"
        iyy="${mass1 / 12.0 * (length1*length1 + width1*width1)}" iyz="0.0"
        izz="${mass1 / 12.0 * (width1*width1 + width1*width1)}"/>
    </inertial>
  </link>

  <link name="link_2">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width2} ${width2} ${length2}"/>
      </geometry>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width2} ${width2} ${length2}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass2}"/>
      <inertia
        ixx="${mass2 / 12.0 * (width2*width2 + length2*length2)}" ixy="0.0" ixz="0.0"
        iyy="${mass2 / 12.0 * (length2*length2 + width2*width2)}" iyz="0.0"
        izz="${mass2 / 12.0 * (width2*width2 + width2*width2)}"/>
    </inertial>
  </link>


  <!-- RGBD camera -->
  <link name="camera_link">
  <collision>
    <origin xyz="-0.016 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="0.036 0.18 0.04"/>
    </geometry>
  </collision>
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://sensor_stick/meshes/asus_xtion.dae"/>
    </geometry>
  </visual>
  <inertial>
    <mass value="${mass_camera}" />
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
  </inertial>
  </link>

  <!--Joints-->
  <joint name="fixed_base_joint" type="fixed">
    <parent link="world"/>
    <child link="link_1"/>
    <origin xyz="0 0 ${length1/2}" rpy="0 0 0"/>
  </joint>

  <joint name="pan_joint" type="continuous">
    <parent link="link_1"/>
    <child link="link_2"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 0 ${length1/2+length2/2}" rpy="0 0 -${pi/2}"/>
  </joint>

  <joint name="tilt_joint" type="continuous">
    <origin xyz="0.05 0 ${length2/2+0.02}" rpy="0 0.5 0" />
    <parent link="link_2" />
    <child link="camera_link" />
    <axis xyz="0 1 0"/>
  </joint>
  <link name="camera_rgb_frame" />
  <joint name="camera_rgb_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0.022 0" />
    <parent link="camera_link" />
    <child link="camera_rgb_frame" />
  </joint>
  <link name="camera_rgb_optical_frame" />
  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin rpy="-1.57079632679 0 -1.57079632679" xyz="0 0 0" />
    <parent link="camera_rgb_frame" />
    <child link="camera_rgb_optical_frame" />
  </joint>
  <link name="camera_depth_frame" />
  <joint name="camera_depth_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0.049 0" />
    <parent link="camera_link" />
    <child link="camera_depth_frame" />
  </joint>
  <link name="camera_depth_optical_frame" />
  <joint name="camera_depth_optical_joint" type="fixed">
    <origin rpy="-1.57079632679 0 -1.57079632679" xyz="0 0 0" />
    <parent link="camera_depth_frame" />
    <child link="camera_depth_optical_frame" />
  </joint>

  <!--Transmission and actuators-->
  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="pan_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="tilt_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</robot>
